language: php

php:
    - 5.0
    - 5.1
    - 5.2
    - 5.3
    - 5.4
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

notifications:
    email: dev@anime-db.org

install:
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar --version
    - php composer.phar install --dev --prefer-dist

script:
    - phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover