language: php

sudo: false

php:
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4
    - 5.3

notifications:
    email: deploy@peter-gribanov.ru

install:
    - composer self-update
    - composer install --dev --prefer-dist

script:
    - phpunit --verbose --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
